### ISSUE TITLE
text 打印中文会乱码

### ISSUE THREAD

**Issue by whqgo** [lilindog/TSPL-Printer#1]

**Comment by Freeman8612** [comment]
我也发现了这个问题，你可以尝试以下方法解决：

1. 修改源码，增加`CODEPAGE  936`指令，具体的参考tspl打印指令的文档。
2. 实测部分打印机，需要自己下载中文字体到Flash后，在打印的时候指定为下载的字体文件。 

*TSPL指令的文档：[http://lilin-nas.quickconnect.cn/sharing/IlAq1Gge7](http://lilin-nas.quickconnect.cn/sharing/IlAq1Gge7)*  

以上是我发现的2个问题，但是在部分品牌打印机上面不会出现这个问题。
我目前测试过3各品牌的打印机；最近新买的打印机还没到，到时候会更新这部分的代码以及说明。   

谢谢你的反馈，欢迎贡献代码。

**Comment by whqgo** [comment]
我使用的是佳博的那款 GP-1324D

**Comment by whqgo** [comment]
text (
        x = 0, 
        y = 0, 
        text = "", 
        scale = 2,
        font='1'
    ) {
        return this.#append(`TEXT ${x},${y},"TSS32.BF2",0,${scale},${scale},"${text}"`);
    }

使用--
 .text(104, 24,'中文',2,'TSS16.BF2')


这样也打印不出来，font 那几个我都试了 不管用

**Comment by whqgo** [comment]
修改，tspl.class.js 中
    /**
     * 单行文本
     * 中文字符等于2个英文字符，字符的打印宽度参考文档对应字体说明
     * tspl与escpos不一样，单行文本不会自动处理换行
     * 
     * @param {Number} [x=0] - x dot 
     * @param {Number} [y=0] - y dot
     * @param {String} [text=""] - 字符串
     * @param {Number} [scale=2] - 缩放倍数，1~15
     * @param {Number} [font=2] - 
     * @returns {Tspl} 详见文档 TEXT 中 的font
     * @public
     */
    text (
        x = 0, 
        y = 0, 
        text = "", 
        scale = 2,
        font='1'
    ) {
        return this.#append(`TEXT ${x},${y},"${font}",0,${scale},${scale},"${text}"`);
    }

这样就可以打印中文了， 我放在最后一个参数了 

  await print
        // .bitmap(5, 0, 10, 80, bitmap)
        .text(104, 24,'中文',2,'TSS24.BF2')
        // .block(20, 50, 200, 100, '中文显示', 2, 8)
        .bar(5, 96, 560, 4)
        // .qrcode(5, 110, "https://github.com/lilindog") // 二维码
        .barcode(20, 110, '128', data.id)
        .bar(5, 290, 560, 4)
        // .text(20, 316, data.lable)
        .print();
